api:
  base_url: "http://192.168.1.120:1234/v1"
  api_key: "lm-studio"
model:
  model: "llama-3.3-70b-instruct"
  model_context_length: 8192
  temperature: 0.7
  classifier: "nlptown/bert-base-multilingual-uncased-sentiment"
  classifier_context_length: 512
  device: "cuda"
database:
  path: "memory.db"
run:
  python_env: "python3"
  code_execution_timeout: 64
  memories_to_remember: 3
  manual_analysis: True
  objective: "Using the Actions local class, create an article about cooking and then save it to a txt file."
