api:
  base_url: "http://localhost:1234/v1"
  api_key: "lm-studio"
model:
  model: ""
  model_context_length: 8192
  temperature: 0.7
  classifier: "nlptown/bert-base-multilingual-uncased-sentiment"
  classifier_context_length: 512
  device: "cpu"
database:
  path: "memory.db"
run:
  python_env: "python3"
  code_execution_timeout: 64
  memories_to_remember: 3
  manual_analysis: False
  objective: "Get the latest news from ansa.it"
